services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: docker
    ports:
      - 5433:5432
